services:
  opengathyr-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opengathyr
    environment:
      - NODE_ENV=production
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped